language: rust
sudo: false

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - RUST_BACKTRACE=1 cargo test --all

notifications:
  email:
    on_success: never
