[package]
name = "synstructure"
version = "0.6.1"
authors = ["Nika Layzell <nika@thelayzells.com>"]

description = "expand_substructure-like helpers for syn macros 1.1 derive macros"
documentation = "https://docs.rs/synstructure"
repository = "https://github.com/mystor/synstructure"
readme = "README.md"
license = "MIT"
keywords = ["syn", "macros", "derive", "expand_substructure", "enum"]

[features]
simple-derive = []

[dependencies]
syn = { version = "0.12", features = ["visit", "extra-traits"] }
proc-macro2 = "0.2.1"
quote = "0.4.2"
unicode-xid = "0.1"

[dev-dependencies]
# Used in the documentation as an example trait crate provider.
example_traits = { path = "example_traits" }

[workspace]
members = ["example_traits", "test_suite", "test_suite/test_macros"]
